[project]
name = "legal-team-mcp"
version = "0.1.0"
description = "MCP server for a legal team to help with drafts"
readme = "README.md"
requires-python = "==3.10.18"
dependencies = [
    "camel-ai",
]
